name: chinesenewyears
favicon: null
layout_spectrum: 0.17993227997794747
typography_spectrum: 0.9506570778321475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3338203076273203
  lightness: 0.09449240728281438
  saturation: 0.5703855834435672
  rhythmicContrast: 0.4619592938106507
purpose: []
